isomerpages/moe-stanthonyspri

_our-anthonian-family/Board Members.md
=> Update file: Board Members

_useful-links/School Supplies and Bus Services.md
=> re-do Bus Fares

_useful-links/School Supplies and Bus Services.md, saps/announcements/_posts/2023-05-04-post-WE STories.md
=> Changes in WeStory

_our-anthonian-family/Anthonian Staff.md
=> Update of Staff List 

_our-anthonian-family/Anthonian Staff.md
=> Update Staff list

_our-anthonian-family/Anthonian Staff.md
=> Update Staff name

saps/announcements/_posts/2023-08-21-post-Important Notice Regarding Teachers' Day Visit for Former Anthonians.md
=> Notice Regarding Teachers' Day Visit

saps/announcements/_posts/2023-08-31-post-SLS System Downtime.md
=> Annoucement 

_useful-links/School Supplies and Bus Services.md
=> new update Textbooks and Uniform Purchase guide

saps/announcements/_posts/2024-01-31-post-Parents Gateway (PG) Down Time.md
=> Parent Gateway downtime annoucement

_about-us/Anthonian Productions.md, _about-us/collection.yml, _our-anthonian-family/Anthonian Staff.md
=> Update Anthonian Staff page

_about-us/Flight Of The Phoenix Productions.md
=> Notice: Coming soon

saps/announcements/_posts/2024-06-24-post-SAPS Tour on 12 July 2024.md
=> Update SAPS Tour

_our-anthonian-family/Anthonian Staff.md
=> Adding Librarian info

_about-us/Anthonian Productions.md
=> Update page -Anthonian Production

_about-us/Anthonian Productions.md, _about-us/SAPS 145th Anniversary Events & Updates.md, _our-anthonian-family/Alumni.md
=> Enbeded video

_about-us/SAPS 145th Anniversary Events & Updates.md
=> Embeded Light The Way Music Video

_cca-clubs-and-societies/English Club.md, _cca-clubs-and-societies/Environmental Science.md, _cca-clubs-and-societies/InfoComm Club.md, _cca-clubs-and-societies/Robotics Club.md, _cca-sports-and-games/Floorball.md, _cca-visual-and-performing-arts/Brass Band.md, _cca-visual-and-performing-arts/Chinese Dance.md, _cca-visual-and-performing-arts/Choir.md, _cca-visual-and-performing-arts/Contemporary Dance.md, _cca-visual-and-performing-arts/Visual Arts.md, _the-anthonian-experience/CCA@SAPS/CCA Policy.md, index.md
Removal of announcements and highlights thumbnails + addition of 'Connect with us'
=> Change to homepage

saps/announcements/_posts/2024-10-14-post-SLS System Upgrade Announcement.md
=> SLS Announcement

_our-anthonian-family/Anthonian Staff.md
I have done the following editings, please help review:
Swap in FT - Siti Raihana (6RE), Nurhamizah (5GE)
fill in email add for Joanne Deng
change Student Counselors to School Counselors
edit staff's email address links
=> Edit staff list

saps/announcements/_posts/2024-01-02-post-MOE Sexuality Education in Schools.md
Please help approve the update
=> Edit Karen's email link in sexuality page

_useful-links/For Parents/Student Care Centre@SAPS.md
a broken link had spotted therefore the link has been removed.
for your review and approve please.
=> Remove a broken link in page Useful link -- Student Care Centre

_our-anthonian-family/Anthonian Staff.md
Add new staff: AE, Mdm Harianti Abdullah
Remove retired staff: OSO, Chee Loy Ying
=> update Anthonian Staff

_our-anthonian-family/Anthonian Staff.md, _useful-links/For Parents/Student Care Centre@SAPS.md
add new OSO info under Operation Team
=> Update new OSO info in Staff list

index.md
=> SAPS Sch tour link

saps/announcements/_posts/2025-06-24-post-SAPS Tour 2025.md
=> add in registration link to Sch Tour poster

_sports-and-games/Football.md
=> Football timing

_sports-and-games/Floorball.md
=> Floorball requested - Change Alternate Friday to Selected Friday
